### ISSUE TITLE
Saved Views disappears

### ISSUE THREAD

**Issue by Jopo-JP** [paulgessinger/swift-paperless#18] opened 2023-06-11 23:43 UTC
Hi there,

I noticed, that if you have some views saved, they will simply disappear.
You can still create new ones and save it, but they won't be displayed.

One the webpage you can still see them, but not in the app.

**Comment by paulgessinger** [comment] 2023-06-12 08:37
Hey @Jopo-JP,

that sounds like a bug. Are there any specific steps to reproduce this? Do you have screenshots maybe to show how this looks like when it happens?

**Comment by paulgessinger** [comment] 2023-08-13 18:57
@Jopo-JP Any tips on how to reproduce this?

**Comment by paulgessinger** [comment] 2024-03-23 20:03
@Jopo-JP can you confirm that you're currently getting this issue?

**Comment by paulgessinger** [comment] 2024-04-14 07:36
I'm closing this for now.

**Closed** 2024-04-14 07:36 UTC
Labels: bug
