### ISSUE TITLE
Scan documents directly from the app

### ISSUE THREAD

**Issue by viktor56240** [paulgessinger/swift-paperless#43] opened 2023-12-20 20:21 UTC
Good morning,
It would be interesting to be able to scan a document directly from the application.
I don't know if this is possible but you would have to use the same function as in the file application.
In any case, congratulations for the rest of the application which is very beautiful and intuitive.
Best wishes

**Comment by joshelboy** [comment] 2023-12-22 10:49
I think what you want to achieve is a duplicate of #23

**Comment by viktor56240** [comment] 2024-01-04 08:08
Yes thanks for your answer

**Closed** 2024-01-04 08:08 UTC
