### ISSUE TITLE
Adding file via camera doesn't work?

### ISSUE THREAD

**Issue by phil-hudson** [paulgessinger/swift-paperless#59] opened 2024-02-12 03:48 UTC
Hey, I'm trying to add some new files into my paperless instance via the app.

After using the plus button, I'm not seeing the document added. Am I using it wrong in some way?

Please see repro attached

https://github.com/paulgessinger/swift-paperless/assets/1914950/9852d8a8-eec9-4dcf-a3bc-5be44fe7b6ff

**Comment by paulgessinger** [comment] 2024-02-12 06:14
Hey @phil-hudson,

After saving, the document creation sheet should pop up. Are you tapping the "Save" button in the bottom left?

**Comment by phil-hudson** [comment] 2024-02-12 07:39
Ah yep, it doesn't show in the video but I tap save, and then the camera is dismissed, but nothing happens. No error on log export too.

Nice work on this project btw!

**Comment by evankrob** [comment] 2024-02-13 00:01
Just to confirm. I have the same issue as Phil-Hudson

**Comment by paulgessinger** [comment] 2024-02-13 07:57
I'll add some logging to the scan workflow, then maybe we can figure this one out.

**Comment by paulgessinger** [comment] 2024-02-13 11:22
@evankrob @phil-hudson Can you check build 39 on TestFlight and send me the logs?

**Comment by ftruzzi** [comment] 2024-02-13 12:28
Hi @paulgessinger, I'm having the same issue. Here are the logs with build 39:

> [13/2/2024, 13:25] [SwiftPaperless] API sequence has reached end (nextPage is nil)
[13/2/2024, 13:25] [SwiftPaperless] API sequence has reached end (nextPage is nil)
[13/2/2024, 13:25] [SwiftPaperless] Fetch all store complete
[13/2/2024, 13:25] [SwiftPaperless] Document scanner receives scan
[13/2/2024, 13:25] [SwiftPaperless] Attempt to make PDF
[13/2/2024, 13:25] [SwiftPaperless] PDF conversion failure: Error Domain=swift_paperless.DocumentScannerView.DocumentScannerError Code=0
[13/2/2024, 13:25] [SwiftPaperless] Requesting log export

Thanks for your help, and nice app! :)

**Comment by paulgessinger** [comment] 2024-02-13 13:44
Ok so the failure seems to be that the PDF creation from the image source fails, which is unfortunate because it's relatively opaque and inside the framework.

**Comment by phil-hudson** [comment] 2024-02-16 07:45
@evankrob probably needs some debugging here: https://github.com/paulgessinger/swift-paperless/blob/97593e3fd483a8f3e35aa466572fec9ab175be7e/swift-paperless/Views/DocumentScannerView.swift#L55

**Comment by paulgessinger** [comment] 2024-02-16 08:25
From the error printout (I should make this more explicit) it looks like the the creation does not fail but the write does.

**Comment by zied-abdellaoui** [comment] 2024-03-08 20:25
Hello , Nice app and thanks for sharing it. I just started using this app last week and I am facing this same issue, I just want to say that I am using a self hosted version of paperless ngx with an nginx reverse proxy in between. When I hit save practically no logs appears in the server side related to the newly created document.

**Comment by paulgessinger** [comment] 2024-03-09 17:45
@zied-abdellaoui Thanks! The lack of logs on the server side is because it seems it crashes when trying to save the captured document, and never gets to uploading it. 

I haven't been able to reproduce it on my end yet however, so haven't managed to find a fix yet. 

Any pointers that could help me try to reproduce this would really help!

**Comment by ItsNotDNS** [comment] 2024-03-10 03:57
I'm seeing this as well.  Trying to figure out if I can suss out any additional information.  I have a self-hosted docker instance, basically stock still at this point.  Both docker and phone are on the same LAN.

**Comment by ItsNotDNS** [comment] 2024-03-10 04:22
Restarted swift and attempted a scan and then collected logs
`
[3/9/2024, 9:20 PM] [SwiftPaperless] Checking login status
[3/9/2024, 9:20 PM] [SwiftPaperless] Initializing ApiRespository with connection <private> <private>
[3/9/2024, 9:20 PM] [SwiftPaperless] Fetch all store request
[3/9/2024, 9:20 PM] [SwiftPaperless] Fetch all store
[3/9/2024, 9:20 PM] [SwiftPaperless] API sequence next task was cancelled.
[3/9/2024, 9:20 PM] [SwiftPaperless] API sequence next task was cancelled.
[3/9/2024, 9:20 PM] [SwiftPaperless] API sequence next task was cancelled.
[3/9/2024, 9:20 PM] [SwiftPaperless] API sequence next task was cancelled.
[3/9/2024, 9:20 PM] [SwiftPaperless] API sequence next task was cancelled.
[3/9/2024, 9:20 PM] [SwiftPaperless] API sequence next task was cancelled.
[3/9/2024, 9:20 PM] [SwiftPaperless] Unable to get current user: Error Domain=NSURLErrorDomain Code=-999 UserInfo={NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>}
[3/9/2024, 9:20 PM] [SwiftPaperless] Fetch all store request
[3/9/2024, 9:20 PM] [SwiftPaperless] Fetch all store
[3/9/2024, 9:20 PM] [SwiftPaperless] Fetch all store complete
[3/9/2024, 9:20 PM] [SwiftPaperless] Fetch all store complete
[3/9/2024, 9:20 PM] [SwiftPaperless] Fetch all store request
[3/9/2024, 9:20 PM] [SwiftPaperless] Fetch all store
[3/9/2024, 9:20 PM] [SwiftPaperless] Backend version info: API version: 5, backend version: 2.5.4
[3/9/2024, 9:20 PM] [SwiftPaperless] API sequence has reached end (nextPage is nil)
[3/9/2024, 9:20 PM] [SwiftPaperless] API sequence fetch was empty
[3/9/2024, 9:20 PM] [SwiftPaperless] API sequence fetch was empty
[3/9/2024, 9:20 PM] [SwiftPaperless] API sequence has reached end (nextPage is nil)
[3/9/2024, 9:20 PM] [SwiftPaperless] API sequence has reached end (nextPage is nil)
[3/9/2024, 9:20 PM] [SwiftPaperless] API sequence has reached end (nextPage is nil)
[3/9/2024, 9:20 PM] [SwiftPaperless] API sequence fetch was empty
[3/9/2024, 9:20 PM] [SwiftPaperless] Fetch all store complete
[3/9/2024, 9:21 PM] [SwiftPaperless] Requesting log export
`

**Comment by ItsNotDNS** [comment] 2024-03-10 04:31
Here the steps I went through, probably not very helpful but here they are anyways.
1. Updated docker host
2. Restarted paperless ngx docker containers
3. Closed swift app on iphone
4. opened swift app on iphone.  I see two documents show up that were previously uploaded to paperless by other methods
5. Click on the + button in top right corner
6. Click 'Scan document'
7. Camera opens, I can aim camera at a document and it aligns the document and isolates it.  Camera view shrinks to the bottom left, camera is still running and screen says 'Ready for next scan.'.  The save goes from grey to white.
8. Click on 'Save'
9. Screen returns to the same dashboard as when I first open up swift and I see the two documents that were originally there.  I see no prompts or notifications that indicate that anything happened after hitting save
10. No processing shows up in paperless ngx

**Comment by paulgessinger** [comment] 2024-03-10 08:47
@ItsNotDNS are you on the TestFlight? The extra logs for the document scanner haven't made it to the App Store version yet.

**Comment by ItsNotDNS** [comment] 2024-03-10 18:39
This time with feeling (with using the testflight app rather than the main app i was using previously).  In the testflight app I also receive a toast stating 'Could not create page in PDF' after hitting the save button.
```
[3/10/2024, 12:36 PM] [General] Checking login status
[3/10/2024, 12:36 PM] [API] Initializing ApiRespository with connection <private> <private>
[3/10/2024, 12:36 PM] [API] Getting backend versions
[3/10/2024, 12:36 PM] [General] Fetch all store request
[3/10/2024, 12:36 PM] [General] Fetch all store
[3/10/2024, 12:36 PM] [API] API sequence next task was cancelled.
[3/10/2024, 12:36 PM] [API] API sequence next task was cancelled.
[3/10/2024, 12:36 PM] [API] API sequence next task was cancelled.
[3/10/2024, 12:36 PM] [API] API sequence next task was cancelled.
[3/10/2024, 12:36 PM] [API] API sequence next task was cancelled.
[3/10/2024, 12:36 PM] [API] API sequence next task was cancelled.
[3/10/2024, 12:36 PM] [API] Caught error fetching <private>: Error Domain=NSURLErrorDomain Code=-999 UserInfo={NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>}
[3/10/2024, 12:36 PM] [General] Unable to get current user: Error Domain=NSURLErrorDomain Code=-999 UserInfo={NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>}
[3/10/2024, 12:36 PM] [API] Getting document sequence for filter
[3/10/2024, 12:36 PM] [General] Fetch all store request
[3/10/2024, 12:36 PM] [General] Fetch all store
[3/10/2024, 12:36 PM] [General] Fetch all store complete
[3/10/2024, 12:36 PM] [General] Fetch all store complete
[3/10/2024, 12:36 PM] [General] Fetch all store request
[3/10/2024, 12:36 PM] [General] Fetch all store
[3/10/2024, 12:36 PM] [API] API sequence fetch was empty
[3/10/2024, 12:36 PM] [API] API sequence has reached end (nextPage is nil)
[3/10/2024, 12:36 PM] [General] App becomes active
[3/10/2024, 12:36 PM] [API] API sequence fetch was empty
[3/10/2024, 12:36 PM] [API] API sequence has reached end (nextPage is nil)
[3/10/2024, 12:36 PM] [API] API sequence has reached end (nextPage is nil)
[3/10/2024, 12:36 PM] [API] Backend version info: API version: 5, backend version: 2.5.4
[3/10/2024, 12:36 PM] [API] API sequence has reached end (nextPage is nil)
[3/10/2024, 12:36 PM] [API] API sequence fetch was empty
[3/10/2024, 12:36 PM] [General] Fetch all store complete
[3/10/2024, 12:36 PM] [API] Get thumbnail
[3/10/2024, 12:36 PM] [API] Get thumbnail
[3/10/2024, 12:36 PM] [General] Document scanner receives scan
[3/10/2024, 12:36 PM] [General] Attempt to make PDF
[3/10/2024, 12:36 PM] [General] PDF conversion failure: Error Domain=swift_paperless.DocumentScannerView.DocumentScannerError Code=0
[3/10/2024, 12:36 PM] [General] Requesting log export
```

**Comment by roycepope** [comment] 2024-03-14 15:38
I am hitting this bug using v1.0.2 downloaded from the iOS App Store

**Comment by redholt** [comment] 2024-03-15 12:08
Same issue for me.
Containers setup the sames as @ItsNotDNS on my NAS. 
Using iPhone 13 Pro on iOS 17.3.1

**Comment by Eng4G3** [comment] 2024-03-19 18:58
Just wanted to add I installed paperless via docker compose for the first time this week - haven't done anything with it yet as I was trying to find the best way to import. I downloaded Swift Paperless via iOS App Store on an iPhone 15 Pro Max and am having the same issue where I save a scan and it doesn't seem to do anything. Happy to provide additional logs / info as needed to help reproduce and fix the issue. :)

**Comment by PTST** [comment] 2024-03-19 19:46
I have submitted a pr #64 with a fix for this issue
It seems to be a problem with the date format used in the file name in some locales using characters that are forbidden in file name (i.e. "/")

**Comment by paulgessinger** [comment] 2024-03-23 19:49
I've merged the fix! It should be available in build 42 on TestFlight.

Could you confirm the issue is gone for you @evankrob @phil-hudson @Eng4G3 @redholt @ItsNotDNS @roycepope @zied-abdellaoui @ftruzzi ?

**Comment by redholt** [comment] 2024-03-23 21:28
Yep, working here @paulgessinger thank you 👍

**Comment by ItsNotDNS** [comment] 2024-03-24 18:05
I can confirm that it's working for me now as well after updating the testflight app.

**Comment by Eng4G3** [comment] 2024-03-24 18:55
I didn't have TestFlight installed, but loaded it and the beta version and it worked for me as well. :)

**Closed** 2024-03-24 19:05 UTC
Labels: bug
