### ISSUE TITLE
ASN number not incrementing

### ISSUE THREAD

**Issue by jphussey** [paulgessinger/swift-paperless#55] opened 2024-01-29 22:49 UTC
Firstly, amazing app does pretty much everything I need and beautifully presented. 

One issue I have is if adding ASN to a document and clicking the +1 I just get 1 rather than the next increment. 

Thanks.

**Comment by paulgessinger** [comment] 2024-02-06 22:16
I think this might be a duplicate of #47. Is this still happening on the TestFlight version?

**Comment by paulgessinger** [comment] 2024-02-08 15:46
Ping @jphussey

**Closed** 2024-03-23 19:56 UTC
